listening-port=3478
tls-listening-port=5349
fingerprint
no-cli
no-loopback-peers
no-multicast-peers
realm=connect.mooz.pro
server-name=connect.mooz.pro
lt-cred-mech
user=turnuser:turnpass
total-quota=0
bps-capacity=0
stale-nonce
no-stdout-log
pidfile=/var/run/turnserver.pid
simple-log
no-tlsv1
no-tlsv1_1
cert=/etc/turn/certs/fullchain.pem
pkey=/etc/turn/certs/privkey.pem
external-ip=${EXTERNAL_IP}

